### PR TITLE
fix(generate): pass a baseQueryFn with --baseQuery

### LINKED ISSUE #33: Cli option --baseQuery generates a custom fetchBaseQuery function call instead of a BaseQueryFn function
# Current behaviour
The following command
```shell
npx @rtk-incubator/rtk-query-codegen-openapi \
--file ./src/services/generated/api.generated.ts \
--baseQuery ./src/services/customFn.ts:customFn \
--hooks \
openapi-schema.yml
```
generates `api.generated.ts` with `customFn` expected to have the same behaviour as `fetchBaseQuery`
```typescript
export const api = createApi({ baseQuery: customFn({ baseUrl: "https://example.com" }), ...})
```
# Proposal
`customFn` could be of type `BaseQueryFn` and the generated file would assign `customFn` to `baseQuery` attribute in the `createApi` option argument.
```typescript
export const api = createApi({ baseQuery: customFn, ... })
```
## Motivations
* It's not really convenient to set baseUrl in the command line 
* Either way It's not convenient to add options to the `customFn` arguments via the cli and would be easier to that in the code
* I think it would make it easier and cleaner to setup axios-like interceptor and add options to `fetch` as in the following example
```typescript
const baseQuery = fetchBaseQuery({
  baseUrl: API_URL,
  credentials: "include",
  prepareHeaders: (headers) => {
    const token = getToken();
    if (token) {
      headers.set("Authorization", token);
    }
    return headers;
  },
});

export const customFn: BaseQueryFn = async (args, api, extraOptions) => {
    const result = await baseQuery(args, api, extraOptions);
    if (result.error && result.error.status === 401) {
      api.dispatch(logout());
    }
    return result;
};
```
Notes: there are some bugs in the documentation related to this : https://rtk-query-docs.netlify.app/api/createApi#basequery

### PR DESCRIPTION
**Pull request by tevariou**
## Fixes
Fixes #33 by @tevariou

## Description
When using the `--baseQuery` cli option like this `--baseQuery ./path/to/customBaseQuery.ts:customBaseQuery`, we get the following output:
```typescript
export const api = createApi({ baseQuery: customBaseQuery({ baseUrl: "https://example.com" }), ...})
```

 This PR changes the behaviour of the `--baseQuery` option and the output now would be:
```typescript
export const api = createApi({ baseQuery: customBaseQuery, ...})
```

The `--baseUrl` option now only apply if `--baseQuery` is not passed. In this case, the default `fetchBaseQuery` will be called with the specified base url.

### CODE REVIEW

File: src/generate.ts [hunk 1]
```diff
@@ -112,17 +112,18 @@ export async function generateApi(
...
+      factory.createObjectLiteralExpression(
+        [
+          factory.createPropertyAssignment(
+            factory.createIdentifier('baseUrl'),
+            factory.createStringLiteral(baseUrl as string)
+          ),
+        ],
+        false
+      ),
+    ]);
```
Comment (phryneas) [inline src/generate.ts:126]:
```suggestion
  const fetchBaseQueryCall = factory.createCallExpression(factory.createIdentifier('fetchBaseQueryCall'), undefined, [
    factory.createObjectLiteralExpression(
      [factory.createPropertyAssignment(factory.createIdentifier('baseUrl'), factory.createStringLiteral(baseUrl))],
      false
    ),
  ]);
```

I think we can keep this just as it is and don't need a function - this will just create an object. It doesn't hurt if it never used later.

Let's just remove the `as string` cast as that doesn't seem necessary any more now.

Also let's make it specific to `fetchBaseQuery` and give it an according name

File: src/generate.ts [hunk 2]
```diff
@@ -137,7 +138,7 @@ export async function generateApi(
           exportName,
           reducerPath,
           createApiFn: factory.createIdentifier('createApi'),
-          baseQuery: baseQueryCall,
+          baseQuery: baseQuery === 'fetchBaseQuery' ? generateBaseQueryCall() : factory.createIdentifier(baseQuery),
```
Comment (phryneas) [inline src/generate.ts:141]:
```suggestion
          baseQuery: baseQuery === 'fetchBaseQuery' ? fetchBaseQueryCall : factory.createIdentifier(baseQuery),
```

**Review by phryneas — CHANGES_REQUESTED** [review]
Maybe also add a warning if both `--baseUrl` and `--baseQuery` are specified as those are essentially exclusive from each other with this change. Providing both doesn't make sense.

**Review by phryneas — APPROVED** [review]
Looks good to me. Your thoughts @msutkowski ?

**Review by msutkowski — APPROVED** [review]
Looks good, thanks!
