### PR TITLE
fix: special chars in params name handling

### LINKED ISSUE #15: Invalid type names?
Hi!

I am running a API-Platform project, that uses a bunch of -,: in the type names, which makes typescript complain *alot* :) 

Stuff like this, any tips on how I can fix it?
image

TSC Complains about the dash, and ] sign, but I have no idea what is needed to fix :/

### LINKED ISSUE #35: parameter name with full stops in them
Hi
I'm investigating using rtk-query-codegen at our work. We currently have a large OpenAPI v2 file generated from a proto definition.
Some of its query parameter names are using a dot notation Eg `filter.name`. 

To replicate more easily I modified the pets swagger file so that `"/pet/findByStatus"` has a parameter `"name": "status.foo",` 

and when I run 
```npm run prepare && npm run test:update```

I see this error being generated:
```
SyntaxError: ',' expected. (10:77)

   9 |         findPetsByStatus: build.query<FindPetsByStatusApiResponse, FindPetsByStatusApiArg>({
> 10 |             query: queryArg => ({ url: `/pet/findByStatus`, params: { status.foo: queryArg.statusFoo } })
     |                                                                             ^
  11 |         })

```
I have tinkered with the code in generate.ts to avoid the error, but then this will quote all parameters regardless of whether they require it or not. 
To be fair I've not even got to the point of integrating the api as I've got some other issues I need to investigate before the generator works.
I guess my question is: is this an acceptable solution to start work on a pull request or am I totally off base with how things should work. 

```
function generateQuerArgObjectLiteralExpression(queryArgs: QueryArgDefinition[], rootObject: ts.Identifier) {
  return factory.createObjectLiteralExpression(
    queryArgs.map(
      (param) => {
        const origName = factory.createIdentifier(param.originalName);
        const name: ts.Identifier = {
          ...origName,
          escapedText: `'${origName.escapedText}'` as any,
        };

        return factory.createPropertyAssignment(
          name,
          factory.createPropertyAccessExpression(rootObject, factory.createIdentifier(param.name))
        )
      }
    )
  );
}
```

### PR DESCRIPTION
**Pull request by tevariou**
## Fixes
#35 and #57 and #59

Please also consider https://github.com/phryneas/oazapfts/pull/2 as well to fix #15

### CODE REVIEW

**Comment by Sigkar** [comment]
Ran into this issue with AWS exported codegen files writing headers as string literals.

**Comment by Sigkar** [comment]
Can confirm this PR fixes the headers as strings issue my organization had, made a fork to build it for now

File: src/generate.ts [hunk 1]
```diff
@@ -240,7 +245,7 @@ export async function generateApi(
     const queryArg: QueryArgDefinitions = {};
     for (const param of parameters) {
       let name = camelCase(param.name);
-      queryArg[name] = {
+      queryArg[param.name] = {
```
Comment (phryneas) [inline src/generate.ts:248]: I'm gonna merge that in but I will add another commit on top of it that will keep the old behaviour for the case that `param.name` matches `/[a-zA-Z][a-zA-Z0-9_]/` to keep the camelcase for the most normal cases.
